// Canonical node + edge ID helpers.
//
// Per 1st principles, every ID in the graph must be
// generated by one of these helpers. Hand-built strings
// are forbidden; integrity tests (tests/test_graph_integrity.py)
// verify every graph_nodes.id matches the canonical
// format.
//
// Format: `versesignal:n:<type>:<slug>` for nodes
//         `versesignal:e:<edge-kind>:<src>:<dst>` for edges
//         `versesignal:ev:<edge-id>:<idx>` for evidence

import type { SourceApi } from "@/lib/types";

const NODE_PREFIX = "versesignal:n";
const EDGE_PREFIX = "versesignal:e";
const EVIDENCE_PREFIX = "versesignal:ev";

// === NODES ===

/** `versesignal:n:song:<song-id>` */
export const nodeSong = (songId: string): string =>
  `${NODE_PREFIX}:song:${songId}`;

/** `versesignal:n:artist:<slug>` (slug from artist name) */
export const nodeArtist = (artistName: string): string =>
  `${NODE_PREFIX}:artist:${slug(artistName)}`;

/** `versesignal:n:event:<event-id>` */
export const nodeEvent = (eventId: string): string =>
  `${NODE_PREFIX}:event:${eventId}`;

/** `versesignal:n:theme:<slug>` (theme slug, e.g., `love`) */
export const nodeTheme = (themeSlug: string): string =>
  `${NODE_PREFIX}:theme:${themeSlug}`;

/** `versesignal:n:entity:<slug>` (entity type + slug) */
export const nodeEntity = (entityType: string, slug: string): string =>
  `${NODE_PREFIX}:entity:${entityType}:${slug}`;

/** `versesignal:n:year:<year>` (year node) */
export const nodeYear = (year: number): string =>
  `${NODE_PREFIX}:year:${year}`;

/** `versesignal:n:region:<code>` (region node) */
export const nodeRegion = (regionCode: string): string =>
  `${NODE_PREFIX}:region:${regionCode.toLowerCase()}`;

// === EDGES ===

/** `versesignal:e:song-theme:<song-id>:<theme>` */
export const edgeSongTheme = (songId: string, themeSlug: string): string =>
  `${EDGE_PREFIX}:song-theme:${songId}:${themeSlug}`;

/** `versesignal:e:song-event:<song-id>:<event-id>:<link-type>` */
export const edgeSongEvent = (
  songId: string,
  eventId: string,
  linkType: string
): string =>
  `${EDGE_PREFIX}:song-event:${songId}:${eventId}:${linkType}`;

/** `versesignal:e:song-entity:<song-id>:<entity-type>:<slug>` */
export const edgeSongEntity = (
  songId: string,
  entityType: string,
  slug: string
): string =>
  `${EDGE_PREFIX}:song-entity:${songId}:${entityType}:${slug}`;

/** `versesignal:e:song-similar:<song-a>:<song-b>` (unordered; both directions exist) */
export const edgeSongSimilar = (songA: string, songB: string): string => {
  const [a, b] = [songA, songB].sort();
  return `${EDGE_PREFIX}:song-similar:${a}:${b}`;
};

/** `versesignal:e:song-artist:<song-id>:<artist-slug>` */
export const edgeSongArtist = (songId: string, artistSlug: string): string =>
  `${EDGE_PREFIX}:song-artist:${songId}:${artistSlug}`;

/** `versesignal:e:song-year:<song-id>:<year>` */
export const edgeSongYear = (songId: string, year: number): string =>
  `${EDGE_PREFIX}:song-year:${songId}:${year}`;

// === EVIDENCE ===

/** `versesignal:ev:<edge-id>:<idx>` (idx is 0-based per edge) */
export const evidenceRow = (edgeId: string, idx: number): string =>
  `${EVIDENCE_PREFIX}:${edgeId}:${idx}`;

// === SLUG HELPER ===

/** Lowercase, replace whitespace + punctuation with `-`, collapse runs. */
export function slug(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

// === VALIDATION ===

const NODE_RE = /^versesignal:n:(song|artist|event|theme|entity|year|region):[a-z0-9][a-z0-9:_\-.]{0,254}$/;
const EDGE_RE = /^versesignal:e:[a-z-]+:[a-z0-9:_\-.]{1,400}$/;
const EVIDENCE_RE = /^versesignal:ev:[a-z0-9:_\-.]+:[0-9]+$/;

/** Returns true if the given ID matches the canonical node format. */
export function isCanonicalNodeId(id: string): boolean {
  return NODE_RE.test(id);
}

/** Returns true if the given ID matches the canonical edge format. */
export function isCanonicalEdgeId(id: string): boolean {
  return EDGE_RE.test(id);
}

/** Returns true if the given ID matches the canonical evidence format. */
export function isCanonicalEvidenceId(id: string): boolean {
  return EVIDENCE_RE.test(id);
}

/** Allowed SourceApi values. Kept here so the helpers are
 * the single source of truth for ID + provenance rules. */
export const SOURCE_API_VALUES: ReadonlyArray<SourceApi> = [
  "musixmatch",
  "songstats",
  "billboard",
  "musicbrainz",
  "wikidata",
  "jam_base",
  "jambase",
  "cyanite",
  "elevenlabs",
  "manual",
  "spacy",
  "gliner",
  "embedding",
  "llm",
  "lexicon",
  "hybrid",
  "human",
] as const;
