// Regenerate lib/song-redirects.ts by comparing the current song
// IDs to what the OLD slug function would have produced. Run this
// if the canonical ID format ever changes again.
//
// Run: npx tsx scripts/regenerate-song-redirects.ts

import { closeDb, getDb, initDb } from "../lib/db";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

/** The old slug function (pre-canonical-id migration) */
function oldSlug(title: string, artist: string): string {
  return `${title}-${artist}`
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function main() {
  initDb();
  const db = getDb();
  const songs = db.prepare("SELECT id, title, artist FROM songs").all() as Array<{
    id: string;
    title: string;
    artist: string;
  }>;

  const redirects: Record<string, string> = {};
  for (const s of songs) {
    const oldSlugVal = oldSlug(s.title, s.artist);
    const oldId = s.id.replace(/:[^:]+$/, `:${oldSlugVal}`);
    if (oldId !== s.id) {
      redirects[oldId] = s.id;
    }
  }

  const lines: string[] = [];
  lines.push("// Legacy song-ID redirects.");
  lines.push("//");
  lines.push("// Per motto_v3 §0.7, never silently break external links. When the");
  lines.push("// canonical ID convention for songs changes (e.g., from a stripped-");
  lines.push("// apostrophe slug to an NFKD-normalized slug), old IDs would 404");
  lines.push("// otherwise.");
  lines.push("//");
  lines.push("// This map is auto-generated by `scripts/regenerate-song-redirects.ts`");
  lines.push("// — do not edit by hand unless the canonical ID format changes again.");
  lines.push("");
  lines.push("const LEGACY_SONG_ID_REDIRECTS: Record<string, string> = {");
  for (const [from, to] of Object.entries(redirects)) {
    lines.push(`  ${JSON.stringify(from)}: ${JSON.stringify(to)},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("/** Returns the canonical (current) song ID for a given request ID, or");
  lines.push(" * the input if no redirect applies. */");
  lines.push("export function resolveSongId(requestedId: string): string {");
  lines.push("  return LEGACY_SONG_ID_REDIRECTS[requestedId] ?? requestedId;");
  lines.push("}");

  const out = lines.join("\n") + "\n";
  const outPath = join(process.cwd(), "lib", "song-redirects.ts");
  writeFileSync(outPath, out, "utf8");
  console.log(`✓ Wrote ${Object.keys(redirects).length} legacy redirects to ${outPath}`);
  closeDb();
}

main();
