// Seed the songs table from data/chart-seed.ts.
// Inserts one row per (year, rank) using a stable slug ID.
//
// Per 1st principles, every graph_nodes.id is generated by
// the canonical helpers in lib/graph/ids.ts. Every edge gets
// ≥1 evidence row. The graph integrity test
// (tests/test_graph_integrity.py) verifies these invariants.

import { closeDb, getDb, initDb } from "../lib/db";
import { CHART_SEED, DEMO_YEARS } from "../data/chart-seed";
import { CHART_HISTORICAL } from "../data/chart-seed-historical";
import { CHART_REGIONAL } from "../data/chart-seed-regional";
import { isProtectedArtist } from "../lib/db/protected-artists";
import {
  nodeArtist,
  nodeSong,
  nodeYear,
  edgeSongArtist,
  edgeSongYear,
  evidenceRow,
  slug as idSlug,
} from "../lib/graph/ids";

function songSlug(title: string, artist: string): string {
  return idSlug(`${title}-${artist}`).slice(0, 80);
}

function songId(year: number, rank: number, title: string, artist: string): string {
  return `versesignal:${year}:${String(rank).padStart(2, "0")}:${songSlug(title, artist)}`;
}

function ensureGraphEdgeColumns(db: ReturnType<typeof getDb>) {
  const cols = (db.prepare("PRAGMA table_info(graph_edges)").all() as { name: string }[]).map((r) => r.name);
  if (!cols.includes("inference_type")) {
    db.exec("ALTER TABLE graph_edges ADD COLUMN inference_type TEXT");
  }
  if (!cols.includes("matched_terms_json")) {
    db.exec("ALTER TABLE graph_edges ADD COLUMN matched_terms_json TEXT");
  }
}

function main() {
  initDb();
  const db = getDb();
  ensureGraphEdgeColumns(db);

  // Clean up: drop old non-canonical performed_by and charted_in edges
  // (and their evidence) before re-seeding with canonical IDs. This
  // migration is idempotent: running the seed twice yields the same DB.
  const orphanEvidence = db.prepare(`
    DELETE FROM evidence
    WHERE edge_id IN (
      SELECT id FROM graph_edges
      WHERE edge_type IN ('performed_by', 'charted_in')
        AND id NOT LIKE 'versesignal:e:song-artist:%'
        AND id NOT LIKE 'versesignal:e:song-year:%'
    )
  `).run();
  const staleChartEdges = db.prepare(`
    DELETE FROM graph_edges
    WHERE edge_type IN ('performed_by', 'charted_in')
      AND id NOT LIKE 'versesignal:e:song-artist:%'
      AND id NOT LIKE 'versesignal:e:song-year:%'
  `).run();
  const staleChartNodes = db.prepare(`
    DELETE FROM graph_nodes
    WHERE (node_type = 'artist' AND id NOT LIKE 'versesignal:n:artist:%')
       OR (node_type = 'year' AND id NOT LIKE 'versesignal:n:year:%')
  `).run();
  if (orphanEvidence.changes || staleChartEdges.changes || staleChartNodes.changes) {
    console.log(
      `↻ Cleaned: ${staleChartEdges.changes} stale chart edges, ` +
      `${staleChartNodes.changes} stale artist/year nodes, ` +
      `${orphanEvidence.changes} orphan evidence rows.`
    );
  }

  const insertSong = db.prepare(`
    INSERT OR REPLACE INTO songs
      (id, title, artist, year, chart_source, chart_rank, region, ingested_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
  `);

  const insertGraphNode = db.prepare(`
    INSERT OR IGNORE INTO graph_nodes (id, node_type, label, properties_json)
    VALUES (?, ?, ?, ?)
  `);

  const insertEdge = db.prepare(`
    INSERT OR IGNORE INTO graph_edges
      (id, src_id, dst_id, edge_type, weight, confidence, source_api, model_version, inference_type, matched_terms_json, explanation)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const insertEvidence = db.prepare(`
    INSERT OR IGNORE INTO evidence
      (id, edge_id, evidence_type, value, source, confidence, created_at)
    VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
  `);

  // Pre-compute the slug form of an artist name (matches nodeArtist in lib/graph/ids.ts)
  // so we can derive the edge-id suffix consistently.
  const seedYear = db.transaction((year: number, entries: typeof CHART_SEED[number]) => {
    for (const e of entries) {
      const id = songId(year, e.rank, e.title, e.artist);
      // Split multi-artist names properly so all collaborators are preserved.
      // Handles: "X, Y and Z" → ["X", "Y", "Z"], "X featuring Y" → ["X", "Y"]
      // Known band names like "Tones and I" bypass splitting.
      const parts = isProtectedArtist(e.artist)
        ? [e.artist]
        : e.artist.split(/\s+(?:feat\.?|featuring|ft\.?|&|and|with)\s+/i).flatMap((p) => p.split(/,\s*/).map((s) => s.trim()).filter(Boolean));
      // Deduplicate case-insensitively, preserving first-encountered casing
      const seenArtists = new Set<string>();
      const allArtists: string[] = [];
      for (const a of parts) {
        const key = a.toLowerCase();
        if (!seenArtists.has(key)) { seenArtists.add(key); allArtists.push(a); }
      }
      const primaryArtist = allArtists[0]!;
      const artistStr = allArtists.join(", ");
      insertSong.run(id, e.title, artistStr, year, "billboard_hot100_ye", e.rank, "US");

      const songNode = nodeSong(id);
      const yearNode = nodeYear(year);
      insertGraphNode.run(songNode, "song", `${e.title} — ${primaryArtist} (${year})`, null);
      insertGraphNode.run(yearNode, "year", String(year), null);

      const allArtistNames = [...new Set([primaryArtist, ...allArtists])];
      const artistCount = allArtistNames.length;
      for (const artistName of allArtistNames) {
        const aNode = nodeArtist(artistName);
        const edgeId = edgeSongArtist(id, idSlug(artistName));
        insertGraphNode.run(aNode, "artist", artistName, null);
        insertEdge.run(
          edgeId,
          songNode,
          aNode,
          "performed_by",
          1.0 / artistCount,
          1.0,
          "manual",
          null,
          "manual_curation",
          null,
          `Artist credit from chart entry. Co-credited: ${artistCount === 1 ? "solo" : `${artistCount} collaborators`}.`
        );
        // Evidence row: chart entry itself is the source.
        insertEvidence.run(
          evidenceRow(edgeId, 0),
          edgeId,
          "chart_era_context",
          `Year-end rank #${e.rank} on Billboard Hot 100 credits "${artistName}" as a performer.`,
          "billboard",
          1.0
        );
      }
      // song → year (charted_in) edge + evidence
      const chartedEdgeId = edgeSongYear(id, year);
      insertEdge.run(
        chartedEdgeId,
        songNode,
        yearNode,
        "charted_in",
        1.0,
        1.0,
        "billboard",
        null,
        "manual_curation",
        null,
        `Year-end rank #${e.rank} on Billboard Hot 100.`
      );
      insertEvidence.run(
        evidenceRow(chartedEdgeId, 0),
        chartedEdgeId,
        "chart_era_context",
        `Year-end rank #${e.rank} on Billboard Hot 100 for year ${year}.`,
        "billboard",
        1.0
      );
    }
  });

  let totalSongs = 0;
  for (const year of DEMO_YEARS) {
    const entries = CHART_SEED[year];
    if (!entries) continue;
    seedYear(year, entries);
    totalSongs += entries.length;
  }

  // === Historical chart-memory mode (Tier 4, 1960s-2017) ===
  // One #1 year-end song per year. Uses a different `chart_source`
  // value so the demo/timeline can distinguish the two corpus
  // windows. Idempotent: INSERT OR REPLACE on the song ID.
  for (const h of CHART_HISTORICAL) {
    seedSingle({
      year: h.year,
      rank: h.rank,
      title: h.title,
      artist: h.artist,
      chart_source: "billboard_yearend_historical",
      region: "US",
      edge_explanation: `Year-end #1 on Billboard Hot 100 for year ${h.year} (historical chart-memory mode).`,
      evidence_value: `Year-end #1 on Billboard Hot 100 (${h.year}) credits "%s" as a performer.`,
      charted_explanation: `Year-end #1 on Billboard Hot 100 for year ${h.year} (historical chart-memory mode).`,
    });
    totalSongs++;
  }

  // === Regional chart inventory (Tier 6 starter) ===
  // Curated starter set of regional chart hits (4 regions × 4 years
  // = 24 songs). This is the minimum needed to demonstrate the
  // regional architecture; a full Tier 6 inventory expansion is
  // tracked as follow-up.
  for (const r of CHART_REGIONAL) {
    seedSingle({
      year: r.year,
      rank: r.rank,
      title: r.title,
      artist: r.artist,
      chart_source: "regional_yearend",
      region: r.region,
      edge_explanation: `Year-end #1 (regional) for ${r.region} (${r.year}).`,
      evidence_value: `Year-end #1 on the ${r.region} chart (${r.year}) credits "%s" as a performer.`,
      charted_explanation: `Year-end #1 on the ${r.region} chart for year ${r.year} (regional inventory).`,
    });
    totalSongs++;
  }

  console.log(
    `✓ Seeded ${totalSongs} songs: ${DEMO_YEARS.length} demo years + ${CHART_HISTORICAL.length} historical + ${CHART_REGIONAL.length} regional.`
  );
  closeDb();
}

interface SeedEntry {
  year: number;
  rank: number;
  title: string;
  artist: string;
  chart_source: string;
  region: string;
  edge_explanation: string;
  evidence_value: string;
  charted_explanation: string;
}

function seedSingle(s: SeedEntry) {
  // ID stability: the demo US spine uses the canonical
  // `versesignal:<year>:<rank>:<slug>` format that the rest of
  // the codebase (queries, redirects, smoke tests) depends on.
  // For non-US regional entries, we add a region prefix to
  // avoid collisions when the same song also charts in the US
  // (e.g., "Blinding Lights" was #1 in 6 different countries in
  // 2020). Historical entries are explicitly US, so they use
  // the canonical format too.
  const id = s.region === "US"
    ? songId(s.year, s.rank, s.title, s.artist)
    : `versesignal:${s.region.toLowerCase()}-${s.year}:${String(s.rank).padStart(2, "0")}:${songSlug(s.title, s.artist)}`;
  const db = getDb();
  const parts = isProtectedArtist(s.artist)
    ? [s.artist]
    : s.artist.split(/\s+(?:feat\.?|featuring|ft\.?|&|and|with)\s+/i).flatMap((p) => p.split(/,\s*/).map((t) => t.trim()).filter(Boolean));
  const seenArtists = new Set<string>();
  const allArtists: string[] = [];
  for (const a of parts) {
    const key = a.toLowerCase();
    if (!seenArtists.has(key)) { seenArtists.add(key); allArtists.push(a); }
  }
  const primaryArtist = allArtists[0]!;
  const artistStr = allArtists.join(", ");

  const insertSong = db.prepare(`
    INSERT OR REPLACE INTO songs
      (id, title, artist, year, chart_source, chart_rank, region, ingested_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
  `);
  insertSong.run(id, s.title, artistStr, s.year, s.chart_source, s.rank, s.region);

  // Per song, prepare the same statements.
  const insertGraphNode = db.prepare(`
    INSERT OR IGNORE INTO graph_nodes (id, node_type, label, properties_json)
    VALUES (?, ?, ?, NULL)
  `);
  const insertEdge = db.prepare(`
    INSERT OR IGNORE INTO graph_edges
      (id, src_id, dst_id, edge_type, weight, confidence, source_api, model_version, inference_type, matched_terms_json, explanation)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);
  const insertEvidence = db.prepare(`
    INSERT OR IGNORE INTO evidence
      (id, edge_id, evidence_type, value, source, confidence, created_at)
    VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
  `);

  const songNode = nodeSong(id);
  const yearNode = nodeYear(s.year);
  insertGraphNode.run(songNode, "song", `${s.title} — ${primaryArtist} (${s.year})`);
  insertGraphNode.run(yearNode, "year", String(s.year));

  for (const artistName of allArtists) {
    const aNode = nodeArtist(artistName);
    const edgeId = edgeSongArtist(id, idSlug(artistName));
    insertGraphNode.run(aNode, "artist", artistName);
    insertEdge.run(
      edgeId,
      songNode,
      aNode,
      "performed_by",
      1.0 / allArtists.length,
      1.0,
      "manual",
      null,
      "manual_curation",
      null,
      s.edge_explanation
    );
    insertEvidence.run(
      evidenceRow(edgeId, 0),
      edgeId,
      "chart_era_context",
      s.evidence_value.replace("%s", artistName),
      "billboard",
      1.0
    );
  }
  const chartedEdgeId = edgeSongYear(id, s.year);
  insertEdge.run(
    chartedEdgeId,
    songNode,
    yearNode,
    "charted_in",
    1.0,
    1.0,
    "billboard",
    null,
    "manual_curation",
    null,
    s.charted_explanation
  );
  insertEvidence.run(
    evidenceRow(chartedEdgeId, 0),
    chartedEdgeId,
    "chart_era_context",
    s.evidence_value.replace("credits \"%s\" as a performer", "is the year-end #1 song"),
    "billboard",
    1.0
  );
}

main();
